# Generated by Django 5.0.3 on 2024-03-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankloan', '0002_customer_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=45)),
                ('acc_number', models.CharField(max_length=16)),
                ('bank_name', models.CharField(max_length=25)),
                ('ifsc_number', models.CharField(max_length=11)),
            ],
        ),
    ]
