# Generated by Django 5.0.3 on 2024-03-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankloan', '0003_payments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payments',
            new_name='payment',
        ),
    ]
